# Generated by Django 4.1.7 on 2023-03-15 17:02

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=20)),
                ('picture', models.URLField()),
                ('sources', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), size=None)),
                ('episodes', models.IntegerField()),
                ('synonyms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('relations', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), default=list, size=None)),
                ('thumbnail', models.URLField()),
                ('season_year', models.IntegerField()),
                ('season', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AnimeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_id', models.IntegerField()),
                ('status', models.CharField(choices=[('watching', 'Watching'), ('completed', 'Completed'), ('dropped', 'Dropped'), ('plan_to_watch', 'Plan to Watch')], default='plan_to_watch', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
