# Generated by Django 4.1.7 on 2023-03-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animedata',
            name='season_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
