# Generated by Django 4.2.1 on 2023-05-11 20:12

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=20)),
                ('picture', models.URLField()),
                ('sources', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), size=None)),
                ('episodes', models.IntegerField()),
                ('synonyms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('relations', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), default=list, size=None)),
                ('thumbnail', models.URLField()),
                ('season_year', models.IntegerField(blank=True, null=True)),
                ('season', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_first', models.CharField(blank=True, max_length=100, null=True)),
                ('name_last', models.CharField(blank=True, max_length=100, null=True)),
                ('name_full', models.CharField(blank=True, max_length=200, null=True)),
                ('name_native', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=1000)),
                ('site', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('format', models.CharField(max_length=100)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('season', models.CharField(blank=True, max_length=100, null=True)),
                ('all_time', models.BooleanField()),
                ('context', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_first', models.CharField(blank=True, max_length=100, null=True)),
                ('name_last', models.CharField(blank=True, max_length=100, null=True)),
                ('name_full', models.CharField(blank=True, max_length=200, null=True)),
                ('name_native', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('is_general_spoiler', models.BooleanField(default=False)),
                ('is_media_spoiler', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_id', models.IntegerField()),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_comments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnimeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_id', models.IntegerField()),
                ('status', models.CharField(choices=[('watching', 'Watching'), ('completed', 'Completed'), ('dropped', 'Dropped'), ('plan to watch', 'Plan to Watch')], default='plan to watch', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('anilist_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title_romaji', models.CharField(max_length=200)),
                ('title_english', models.CharField(blank=True, max_length=200, null=True)),
                ('title_native', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date_year', models.IntegerField(blank=True, null=True)),
                ('start_date_month', models.IntegerField(blank=True, null=True)),
                ('start_date_day', models.IntegerField(blank=True, null=True)),
                ('end_date_year', models.IntegerField(blank=True, null=True)),
                ('end_date_month', models.IntegerField(blank=True, null=True)),
                ('end_date_day', models.IntegerField(blank=True, null=True)),
                ('season', models.CharField(blank=True, max_length=50, null=True)),
                ('season_year', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(max_length=200)),
                ('format', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('episodes', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('chapters', models.IntegerField(blank=True, null=True)),
                ('volumes', models.IntegerField(blank=True, null=True)),
                ('is_adult', models.BooleanField(default=False)),
                ('average_score', models.IntegerField(blank=True, null=True)),
                ('popularity', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(blank=True, default='UNKNOWN', max_length=100, null=True)),
                ('country_of_origin', models.CharField(max_length=2)),
                ('cover_image_extra_large', models.URLField()),
                ('cover_image_large', models.URLField()),
                ('cover_image_medium', models.URLField()),
                ('cover_image_color', models.CharField(blank=True, max_length=50, null=True)),
                ('banner_image', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('trailer', models.URLField(blank=True, null=True)),
                ('characters', models.ManyToManyField(related_name='anime_characters', to='anihub.character')),
                ('external_links', models.ManyToManyField(related_name='anime_external_links', to='anihub.externallink')),
                ('genres', models.ManyToManyField(related_name='anime_genres', to='anihub.genre')),
                ('rankings', models.ManyToManyField(related_name='anime_rankings', to='anihub.ranking')),
                ('staff', models.ManyToManyField(related_name='anime_staff', to='anihub.staff')),
                ('studios', models.ManyToManyField(related_name='anime_studios', to='anihub.studio')),
                ('tags', models.ManyToManyField(related_name='anime_tags', to='anihub.tag')),
            ],
        ),
    ]
